### ISSUE TITLE
Wildcard Let's Encrypt SSL certificate for Galaxy Interactive Environments

### ISSUE THREAD

**Issue by torfinnnome** [elixir-no-nels/usegalaxy#10]
We need a wildcard DNS record for our Galaxy servers (main and test) and a method for obtaining a wildcard SSL certificate for both.

Preferably configured so we can use certbot via Ansible.

https://training.galaxyproject.org/training-material/topics/admin/tutorials/interactive-tools/tutorial.html
https://certbot.eff.org/docs/using.html#dns-plugins

@olsarnow, are you the hostmaster@usegalaxy.no? Could you assist?

**Comment by obrehmer** [comment]
Hi Torfinn,

Unfortunately, I am not the hostmaster of usegalaxy.no. It has been set up before my time. I'm sorry. I'll ask Kjell about that and come back afterwards.

BR Olaf

**Comment by torfinnnome** [comment]
Ok.

@kjellp: What is needed, it seems, is to create the new zones 'interactivetool.usegalaxy.no' and interactivetool.test.usegalaxy.no'. Delegate these to a NS where we can do rfc2136 (dynamic DNS updates) using the rfc2136 plugin from certbot. I.e. PowerDNS and BIND should support this.

domeneshop.no does not support rfc2136. Can we use the nameservers at uib.no for this?

**Comment by torfinnnome** [comment]
I guess it would be even easier to just move the NS of usegalaxy.no to Cloudflare. Free NS hosting, and there exists a certbot plugin.

**Comment by obrehmer** [comment]
Hi Torfinn,
I got access to the domeneshop tool, I'll check it and give you feedback asap.
Have a good start in the new week!
Olaf

ps. You added my personal github account with my private email to this repo. Maybe we can switch to olaf.sarnow@uib.no or do I need to create a 2nd github account for that? :)

**Comment by torfinnnome** [comment]
@olsarnow; Great, thanks! Do ask if you have questions. I use Domeneshop for registry services, and CloudFront for NS, for my personal domains.

We should be moving this repo to a new usegalaxy-no organization soon, so we can add you there when you sort of your GitHub account(s). :-)

**Comment by obrehmer** [comment]
Do you mean Cloudfront or Cloudflare? Cloudflare is correct, isn't it?

**Comment by torfinnnome** [comment]
Sorry, meant Cloudflare, yes.

**Comment by obrehmer** [comment]
Yes, cloudflare works great. Good idea! I'll discuss it with Kjell.

**Comment by obrehmer** [comment]
Hi Torfinn,

who of us will drive the cloudflare topic?
Shall I do it?

BR,
Olaf

**Comment by torfinnnome** [comment]
@olsarnow Yes, I think it makes sense for you to manage it?

**Comment by obrehmer** [comment]
> @olsarnow Yes, I think it makes sense for you to manage it?

Ok I'll do. I take on this task.

**Comment by olafsarnow** [comment]
Hi Torfinn,

this is my correct github account. The other one is just for private things. It would be great, if you can change it here :-) Thanks a lot! 

Olaf

**Comment by olafsarnow** [comment]
Status update:

- I've created a cloudflare account for usegalaxy.no
- i will check the dns zone files again 
- switch to cloudflare DNS on 23.4.2020
