### ISSUE TITLE
Web logging/analytics

### ISSUE THREAD

**Issue by torfinnnome** [elixir-no-nels/usegalaxy#13]
Do we go with Matomo?

If so, we need to set up
- [ ] usegalaxy.no
- [x] test.usegalaxy.no

**Comment by torfinnnome** [comment]
@kidanem Any comments on this? Do you still host a service we can use?

**Comment by kidanem** [comment]
We had an instance a while ago (it used to be called Piwik) but not anymore (it died when the then-sys-admin left)

It will be nice to have as an extension of the monitoring-as-a-service stack. I will setup something and get back to you by next week

**Comment by bruggerk** [comment]
I assume you mean Matomo, I think the only other one is google-analytics. 

I had a quick look at matomo and by the looks use mysql so we would need to support that as well on the db-server (easy). The installation seems simple from the documentation,  though it is all click in a browser

I suggest we try it and add a the tracking to the welcome page and see what it looks like. Should be fairly simple

**Comment by bruggerk** [comment]
there are load of roles, this one looks decent: https://git.coop/webarch/matomo

**Comment by kidanem** [comment]
I was thinking of setting it as a general service in WP2 and not just for the usegalaxy . . .
but, I suggest you go for it and explore. Where it should eventually reside can be **_negotiated_**
