### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by bruggerk** [elixir-no-nels/usegalaxy#23]
**General:**
- [x] Full disk (90%?)
- [x] High CPU load 

**Galaxy-server:**
- [x] Slurm node down

**Slurm-node:**

**Database-server:**

**Comment by torfinnnome** [comment]
Initial draft of Alerts dashboard: https://maas-test.bioinfo.no/grafana/d/000000153/alerts?orgId=1&refresh=5m

But, hohum, it seems both test and production sites use same influxdb database? Is this a feature or a bug?

**Comment by bruggerk** [comment]
Created new database for test
