### ISSUE TITLE
Service monitoring

### ISSUE THREAD

**Issue by torfinnnome** [elixir-no-nels/usegalaxy#30]
We need to monitor services, including fail2ban (and cvmfs), which was currently inactive:

```
slurm $ systemctl status fail2ban
- fail2ban.service - Fail2Ban Service
   Loaded: loaded (/usr/lib/systemd/system/fail2ban.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: man:fail2ban(1)
```

Perhaps using Telegraf, and use Grafana for altering?

Any takers?

**Comment by bruggerk** [comment]
Can look into this one, need it for nga as well
/k

**Comment by torfinnnome** [comment]
This should be operational now, right @bruggerk ? Can close this issue?

**Comment by bruggerk** [comment]
yes it is done
