### ISSUE TITLE
Increase cvmfs cache

### ISSUE THREAD

**Issue by torfinnnome** [elixir-no-nels/usegalaxy#31]
The STAR hg38 database is roughly 30 GB, and hosted on /cvmfs/.

We should increase the cvmfs cache, to fit more data. Optimally a few hundred GBs?

**Comment by bruggerk** [comment]
Are we using the wrong partition? 
There is a big (/dev/vdc1) partion, and the which would fit with the
design document saying we should have  1TB for /cvmfs

/k

**Comment by bruggerk** [comment]
My bad, yes increase it. 
But the cvmfs partition setup does look wrong regardless.
/k

**Comment by torfinnnome** [comment]
Yes, the /cvmfs/data.usegalaxy.no/ is currently not working. Probably a cert/key-related issue. I'll look into it.

**Comment by torfinnnome** [comment]
cvmfs issue fixed by https://github.com/usegalaxy-no/infrastructure-playbook/commit/de065134959c8ca660db9ab05ce9803cda99fc9c.
