### ISSUE TITLE
Read-only permissions breaks Ansible deploy on test. (17/03/21 12:40)

### ISSUE THREAD

**Issue by emrobe** [elixir-no-nels/usegalaxy#50]
TASK [Make sure galaxy owns tool-data] **********************************************************************************************************************************
fatal: [test.usegalaxy.no]: FAILED! => changed=false 
  gid: 991
  group: cvmfs
  mode: '0664'
  msg: 'chown failed: [Errno 30] Read-only file system: ''/srv/galaxy/server/tool-data/Araly1/bwa_mem_index/Araly1/../../../../../../../cvmfs/data.galaxyproject.org/byhand/Araly1/seq/Araly1.fa'''
  owner: cvmfs
  path: /srv/galaxy/server/tool-data/Araly1/bwa_mem_index/Araly1/../../../../../../../cvmfs/data.galaxyproject.org/byhand/Araly1/seq/Araly1.fa
  secontext: system_u:object_r:fusefs_t:s0
  size: 209881243
  state: file
  uid: 994

**Comment by torfinnnome** [comment]
Should be fixed now. https://github.com/usegalaxy-no/infrastructure-playbook/commit/354acfd02131b3fc04897de24f754f8c73d98237
